### ISSUE TITLE
About the inference time

### ISSUE THREAD

**Issue by jiujing23333** [philferriere/tfoptflow#1]
An impressive work. I have some questions about inference time. It seems to be a lot slower than official caffe version. Do you consider the time of data loading? Or tensorflow is so slower than caffe!

**Comment by philferriere** [comment]
Thank you for your kind words, @jiujing23333 

First, please note that this implementation is, by design, portable, i.e., it doesn't use any user-defined CUDA kernels whereas the official NVidia implementation does. Ours will work on any OS and any hardware configuration (even one without a GPU) that can run TensorFlow.

Second, the timing numbers we report are the inference number of the models trained on `FlyingChairs` and `FlyingThings3DHalfRes`. These are models that you can train longer if you want to, or finetune using an additional dataset, should you want to do so. In other words, **these graphs haven't been frozen yet**.

In a typical production environment, you would freeze the model after final training/finetuning and optimize the graph to whatever platform(s) you need to distribute them on using TensorFlow XLA or TensorRT. In that important context, **the inference numbers we report on unoptimized graphs are rather meaningless**.

Additionally, nothing stops you either from forking this code and replacing the most compute intensive tensor ops with CUDA kernels of your own, once you've decided which platform you'll be shipping on.

I hope this answers your concerns.
