### ISSUE TITLE
All pretrained models not available

### ISSUE THREAD

**Issue by rajat95** [philferriere/tfoptflow#2]
Hi,

Some of the models seem to be missing from the link shared, for instance pwcnet-lg-6-2-cyclic-chairsthingsmix. Can you please update? 

Thanks for great work btw

**Comment by philferriere** [comment]
Thanks for the kind words, @rajat95 

The "cyclic" training schedule is here only for quick experimentation, should you want to test a quick modification of your own of the PWC-Net architecture. Ultimately, the **only** PWC-Net models you should be using are the ones trained using the "multisteps" schedule.

We've made available our multistep models, that are far superior to the models trained using the cyclic schedule. You can still train those models longer if you want to, or finetune them to your own dataset, using whatever training schedule you want but, at least, you will be starting with the best models we could train ourselves.

We are also generating two models (a small and a large PWC-Net) using **mixed-precision training**. These models (that use FP16 input images instead of FP32 images) will be available within two weeks.

Hope this clarifies everything.
