### ISSUE TITLE
scale the ground truth flow by 20

### ISSUE THREAD

**Issue by yiyang811** [philferriere/tfoptflow#5]
Thank you for the  awesome work.

I have a question:
The authors scaled the ground truth flow by 20  in their paper. 
However, I didn't find the scale operation  in this project? Am I missing anything?

Thank you.

**Comment by philferriere** [comment]
Hi @yiyang811

Indeed, we do not divide the groundtruth u,v vectors by 20. Our code does **not** use a bilinear filter to upsample low-resolution flows and features in its main loop. Instead, we use `tf.layers.conv2d_transpose()`. This operator performs the same function (upsampling), but **it learns the weights** of the upsampling filter. Our assertion is that, no matter what constant we multiply or divide scaled flows by, the optimizer will simply work with/around/against the arbitrary scaling factors and come up with what it believes are the best upsampling weights through backprop anyway. Whenever we use `tf.image.resize_bilinear()`, however, as in `pwcnet_loss(`) for instance, or when generating the final full-res predicted flow, we **do** scale the flows by the appropriate factor because the bilinear filter uses weights determined by the dimension scaling ratio.

That being said, there still is a glaring **discrepancy** between our explanation above and the code in `def nn(self, x_tnsr, name='pwcnet')` , inside the `else` statement below:

```python
    if lvl == self.opts['pyr_lvls']:
        # Compute the cost volume
        corr = self.corr(c1[lvl], c2[lvl], lvl)

        # Estimate the optical flow
        upfeat, flow = self.predict_flow(corr, None, None, None, lvl)
    else:
        # Warp level of Image1's using the upsampled flow
        scaler = 20. / 2**lvl  # scaler values are 0.625, 1.25, 2.5, 5.0
        warp = self.warp(c2[lvl], up_flow * scaler, lvl)

        # Compute the cost volume
        corr = self.corr(c1[lvl], warp, lvl)

        # Estimate the optical flow
        upfeat, flow = self.predict_flow(corr, c1[lvl], up_flow, up_feat, lvl)
```

If that discrepancy will keep you awake at night, we humbly suggest one of these two approaches:

a) retrain the models, dividing the groundtruth vectors by 20 and multiplying the final full-res predicted flow at the application level;

b) go all in, and replace the original code in `def nn(self, x_tnsr, name='pwcnet')` with the following:

```python
with tf.variable_scope(name):

    # Extract pyramids of CNN features from both input images (1-based lists))
    c1, c2 = self.extract_features(x_tnsr)

    flow_pyr = []

    for lvl in range(self.opts['pyr_lvls'], self.opts['flow_pred_lvl'] - 1, -1):

        if lvl == self.opts['pyr_lvls']:
            # Compute the cost volume
            corr = self.corr(c1[lvl], c2[lvl], lvl)

            # Estimate the optical flow
            upfeat, flow = self.predict_flow(corr, None, None, None, lvl)
        else:
            # Warp level of Image1's using the upsampled flow
            warp = self.warp(c2[lvl], up_flow, lvl)

            # Compute the cost volume
            corr = self.corr(c1[lvl], warp, lvl)

            # Estimate the optical flow
            upfeat, flow = self.predict_flow(corr, c1[lvl], up_flow, up_feat, lvl)

        _, lvl_height, lvl_width, _ = tf.unstack(tf.shape(c1[lvl]))

        if lvl != self.opts['flow_pred_lvl']:
            if self.opts['use_res_cx']:
                flow = self.refine_flow(upfeat, flow, lvl)

            # Upsample predicted flow and the features used to compute predicted flow
            flow_pyr.append(flow)

            up_flow = self.deconv(flow, lvl, 'up_flow')
            up_feat = self.deconv(upfeat, lvl, 'up_feat')
        else:
            # Refine the final predicted flow
            flow = self.refine_flow(upfeat, flow, lvl)
            flow_pyr.append(flow)

            # Upsample the predicted flow (final output) to match the size of the images
            scaler = 2**self.opts['flow_pred_lvl']
            if self.dbg:
                print(f'Upsampling {flow.op.name} by {scaler} in each dimension.')
            size = (lvl_height * scaler, lvl_width * scaler)
            flow_pred = tf.image.resize_bilinear(flow, size, name="flow_pred") * scaler
            break

    return flow_pred, flow_pyr
```

After training, all other things being equal, you should observe very similar performance results. If not, our analysis will have been disproved and you should feel free to re-open this issue for further investigation.

Hope this helps!

**Comment by hubohubohubo** [comment]
Thanks for explanation. But I'm still confused about this sentence:

> we do scale the flows by the appropriate factor because the bilinear filter uses weights determined by the dimension scaling ratio

Could you please expain it further or with a simple example? Thx 😄

@philferriere
